### ISSUE TITLE
HTML rendering

### ISSUE THREAD

**Issue by McStuffins** [vityavv/simple-pastebin#2]
You could read the file sync initially before the server starts listening so you have the file in ram and increase response times.

**Comment by vityavv** [comment]
Which file?

**Comment by McStuffins** [comment]
Your index.html file is read every time a request to the route is made which is inefficient. I think that it would be better to simply store it in RAM, but be careful with ram. You could also create a pipe response with the fs module.

**Comment by vityavv** [comment]
You are right

**Comment by McStuffins** [comment]
Do you want to make the PR or me?

**Comment by McStuffins** [comment]
You could simply pipe the response, but I do not think that you understood what I was saying.. I will try again. 
```
const readFile = util.promisify(fs.readFile)
// do a bunch of other stuff except listen
readFile('index.html').then(function () { http(s).listen(8080) })
```
I would prefer the response to be something like this:
```
const fs = require('fs')
http(s).createServer(function (req, res) {
    if(req.path === '/') {
        res.pipe(fs.createReadStream('index.html'))
    }
})
```
I am not sure if that is proper, but the concept is there. It would free the event loop and listen immediately requiring no time for server bootup.

**Comment by vityavv** [comment]
I don't think that the res.pipe would be any faster (still reading the file in full---and traditional http can't support two connections at the same time

however, you're right about the first one\

**Comment by McStuffins** [comment]
I am pretty sure that res.pipe would allow you to send chunked responses using little to no ram

**Comment by vityavv** [comment]
you're right about the ram, doubt it would be faster though. I think I'm gonna go with the option of reading the file at the beginning to cache it
